<a href="https://colab.research.google.com/github/odmina/misbehaving_armadillos/blob/main/2021_07_13_Dataset-varients-layer-information.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview
The following notebook loads data from single behavioral session (one mouse) and one imaging experiment (just one plane) associated with that session to plot stimulus, licks and reward data and neural activity (one selected neuron). 

# Set up environment and import packages

We have built a package called `mindscope_utilities` which contains some useful convenience functions. The `allenSDK` is a dependency of this package and will be automatically installed when you install `mindscope_utilities` per the instrutions below.

We will first install `mindscope_utilities` into our colab environment by running the commands below. When this cell is complete, click on the `RESTART RUNTIME` button that appears at the end of the output. Note that running this cell will produce a long list of outputs and some error messages. Clicking `RESTART RUNTIME` at the end will resolve these issues. 

You can minimize the cell after you are done to hide the output. 

#### Install necessary packages

In [1]:
!python -m pip install --upgrade pip
!pip install mindscope_utilities --upgrade

     |████████████████████████████████| 1.6MB 8.6MB/s 
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
     |████████████████████████████████| 73 kB 1.6 MB/s 
     |████████████████████████████████| 1.7 MB 13.5 MB/s 
     |████████████████████████████████| 3.4 MB 46.5 MB/s 
     |████████████████████████████████| 149 kB 55.6 MB/s 
     |████████████████████████████████| 10.4 MB 50.7 MB/s 
     |████████████████████████████████| 54 kB 3.0 MB/s 
     |████████████████████████████████| 47.4 MB 28 kB/s 
     |████████████████████████████████| 20.1 MB 136 kB/s 
     |████████████████████████████████| 42 kB 1.3 MB/s 
     |████████████████████████████████| 130 kB 57.5 MB/s 
     |████████████████████████████████| 1.3 MB 28.5 MB/s 
     |████████████████████████████████| 3.4 MB 31.6 MB/s 
     |████████████████████████████████| 2.9 MB 31.7 MB/s 
     |████████████████████████████████| 4.3 MB 32.6 MB/s 
     |████████████████████

#### Next we will import packages we need later in the notebook

In [1]:
import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt

import mindscope_utilities
import mindscope_utilities.visual_behavior_ophys as ophys

from allensdk.brain_observatory.behavior.behavior_project_cache import VisualBehaviorOphysProjectCache

pd.set_option('display.max_columns', 500)

# Load the session and experiment summary tables

We download the data cache:

- `ophys_session_table` contains data describing imaging sessions - one session can contain more than one imaging experiment (more than one plane), and not all behavioral session are accompanied by imaging. contains metadata describing imaging sessions. If more than one plane was imaged during a session, one ophys session id will be associated multiple *ophys experiment ids*. Each ophys session id will also have a unique *behavior session id*
- `behavior_session_table` contains metadata describing behavioral sessions, which may or may not be during imaging. Behavior session ids that do not have *ophys session ids* were training sessions
- `ophys_experiment_table` contains metadata describing imaging experiments (aka imaging planes). When mesoscope is used, one ophys session may contain up to 8 unique experiments (two visual areas by four imaging depths). Some imaging planes may not be released due to quality control issues, thus each ophys session id is associated with anywhere from one to eight unique *experiment ids*. Ophys experiment ids are unique and do not repeat across sessions. To find the same imaging plane that was matched across multiple sessions, use the *ophys_container_id* column that can be found in both ophys_session_table and ophys_experiment_table

In [2]:
data_storage_directory = "/temp" # Note: this path must exist on your local drive
cache = VisualBehaviorOphysProjectCache.from_s3_cache(cache_dir=data_storage_directory)

ophys_session_table.csv: 100%|██████████| 165k/165k [00:00<00:00, 2.99MMB/s]
behavior_session_table.csv: 100%|██████████| 885k/885k [00:00<00:00, 12.1MMB/s]
ophys_experiment_table.csv: 100%|██████████| 336k/336k [00:00<00:00, 4.79MMB/s]


Then we can access the session and experiment tables directly.

Note that a 'session' is a single behavioral session. Sessions that are performed on the mesoscope will have multiple (up to 8) 'experiments' associated with them, where an experiment is a distinct imaging plane. 

In [5]:
session_table = cache.get_ophys_session_table()
experiment_table = cache.get_ophys_experiment_table()
behavior_session_table = cache.get_behavior_session_table()

We can then view the contents of the session table. Note that this contains a lot of useful metadata about each session. One of the columns, `ophys_experiment_id` provides a list of the experiments (aka imaging planes) that are associated with each session.

In [167]:
session_table.head()

equipment_name  \
ophys_session_id                  
951410079                MESO.1   
952430817                MESO.1   
954954402                MESO.1   
955775716                MESO.1   
957020350                MESO.1   

                                                  full_genotype  mouse_id  \
ophys_session_id                                                            
951410079         Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
952430817         Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
954954402         Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
955775716         Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
957020350         Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   

                               reporter_line     driver_line sex  age_in_days  \
ophys_session_id                                                                
951410079         Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F        206.0   
952430817         Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F        209.0   
954954402         Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F        210.0   
955775716         Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F        212.0   
957020350         Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F        213.0   

                      cre_line indicator  session_number  \
ophys_session_id                                           
951410079         Sst-IRES-Cre   GCaMP6f             1.0   
952430817         Sst-IRES-Cre   GCaMP6f             2.0   
954954402         Sst-IRES-Cre   GCaMP6f             3.0   
955775716         Sst-IRES-Cre   GCaMP6f             3.0   
957020350         Sst-IRES-Cre   GCaMP6f             4.0   

                  prior_exposures_to_session_type  \
ophys_session_id                                    
951410079                                       0   
952430817                                       0   
954954402                                       0   
955775716                                       1   
957020350                                       0   

                  prior_exposures_to_image_set  prior_exposures_to_omissions  \
ophys_session_id                                                               
951410079                                 65.0                             0   
952430817                                 66.0                             1   
954954402                                 67.0                             2   
955775716                                 68.0                             3   
957020350                                  0.0                             4   

                  behavior_session_id  \
ophys_session_id                        
951410079                   951520319   
952430817                   952554548   
954954402                   953982960   
955775716                   956010809   
957020350                   957032492   

                                                ophys_experiment_id  \
ophys_session_id                                                      
951410079         [951980471, 951980473, 951980475, 951980479, 9...   
952430817              [953659743, 953659745, 953659749, 953659752]   
954954402         [958527464, 958527471, 958527474, 958527479, 9...   
955775716                         [956941841, 956941844, 956941846]   
957020350         [957759562, 957759564, 957759566, 957759570, 9...   

                                                 ophys_container_id  \
ophys_session_id                                                      
951410079         [1018028339, 1018028342, 1018028345, 101802835...   
952430817          [1018028339, 1018028345, 1018028354, 1018028357]   
954954402         [1018028339, 1018028342, 1018028345, 101802835...   
955775716                      [1018028339, 1018028342, 1018028345]   
957020350         [1018028339, 1018028342, 1018028345, 101802835...   

                         

The experiment table has one row per experiment. Note that the `ophys_session_id` column links each experiment to its associated session in the session_table.

In [37]:
experiment_table.head()

equipment_name  \
ophys_experiment_id                  
951980471                   MESO.1   
951980484                   MESO.1   
951980473                   MESO.1   
951980479                   MESO.1   
951980475                   MESO.1   

                                                     full_genotype  mouse_id  \
ophys_experiment_id                                                            
951980471            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
951980484            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
951980473            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
951980479            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
951980475            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   

                                  reporter_line     driver_line sex  \
ophys_experiment_id                                                   
951980471            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   
951980484            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   
951980473            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   
951980479            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   
951980475            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   

                     age_in_days      cre_line indicator  session_number  \
ophys_experiment_id                                                        
951980471                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   
951980484                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   
951980473                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   
951980479                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   
951980475                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   

                     prior_exposures_to_session_type  \
ophys_experiment_id                                    
951980471                                          0   
951980484                                          0   
951980473                                          0   
951980479                                          0   
951980475                                          0   

                     prior_exposures_to_image_set  \
ophys_experiment_id                                 
951980471                                    65.0   
951980484                                    65.0   
951980473                                    65.0   
951980479                                    65.0   
951980475                                    65.0   

                     prior_exposures_to_omissions  ophys_session_id  \
ophys_experiment_id                                                   
951980471                                       0         951410079   
951980484                                       0         951410079   
951980473                                       0         951410079   
951980479                                       0         951410079   
951980475                                       0         951410079   

                     behavior_session_id  ophys_container_id  \
ophys_experiment_id                                            
951980471                      951520319          1018028342   
951980484                      951520319          1018028351   
951980473                      951520319          1018028345   
951980479                      951520319          1018028354   
951980475                      951520319          1018028339   

                                 project_code  imaging_depth  \
ophys_experiment_id                                            
951980471            VisualBehaviorMultiscope            150   
951980484            VisualBehaviorMultiscope             75   
951980473            VisualBehaviorMultiscope            225   
951980479            VisualBehaviorMultiscope            150   
951980475            VisualBehaviorMultiscope             75   



Table for Single Plane- VisualBehaviorTask1B dataset
-plot imaging depth and targeted structure




In [157]:
SP_VT1B_table = experiment_table[experiment_table['project_code'] == 'VisualBehaviorTask1B']
SP_VT1B_table.head()

equipment_name  \
ophys_experiment_id                  
993862620                  CAM2P.4   
994053903                  CAM2P.4   
994278281                  CAM2P.4   
994790561                  CAM2P.4   
994955425                  CAM2P.4   

                                                     full_genotype  mouse_id  \
ophys_experiment_id                                                            
993862620            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    476970   
994053903            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    476970   
994278281            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    476970   
994790561            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    476970   
994955425            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    476970   

                                  reporter_line     driver_line sex  \
ophys_experiment_id                                                   
993862620            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   
994053903            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   
994278281            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   
994790561            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   
994955425            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   

                     age_in_days      cre_line indicator  session_number  \
ophys_experiment_id                                                        
993862620                  194.0  Sst-IRES-Cre   GCaMP6f             1.0   
994053903                  195.0  Sst-IRES-Cre   GCaMP6f             2.0   
994278281                  196.0  Sst-IRES-Cre   GCaMP6f             3.0   
994790561                  199.0  Sst-IRES-Cre   GCaMP6f             3.0   
994955425                  200.0  Sst-IRES-Cre   GCaMP6f             4.0   

                     prior_exposures_to_session_type  \
ophys_experiment_id                                    
993862620                                          0   
994053903                                          0   
994278281                                          0   
994790561                                          1   
994955425                                          0   

                     prior_exposures_to_image_set  \
ophys_experiment_id                                 
993862620                                    39.0   
994053903                                    40.0   
994278281                                    41.0   
994790561                                    42.0   
994955425                                     0.0   

                     prior_exposures_to_omissions  ophys_session_id  \
ophys_experiment_id                                                   
993862620                                       0         993727065   
994053903                                       1         993984066   
994278281                                       2         994199725   
994790561                                       3         994731371   
994955425                                       4         994883056   

                     behavior_session_id  ophys_container_id  \
ophys_experiment_id                                            
993862620                      993766500           991913453   
994053903                      993995204           991913453   
994278281                      994210659           991913453   
994790561                      994743822           991913453   
994955425                      994894518           991913453   

                             project_code  imaging_depth targeted_structure  \
ophys_experiment_id                                                           
993862620            VisualBehaviorTask1B            275               VISp   
994053903            VisualBehaviorTask1B            275               VISp   
994278281            VisualBehaviorTask1B            275               VISp   
994790561            VisualBehaviorTask1B            2

In [158]:
SP_VT1B_table.imaging_depth.unique()

array([275, 175, 375])

In [159]:
SP_VT1B_table.targeted_structure.unique()

array(['VISp'], dtype=object)

In [160]:
SP_VT1b_VIP = SP_VT1B_table[SP_VT1B_table['cre_line'] == 'Vip-IRES-Cre']
SP_VT1b_VIP.imaging_depth.unique()

array([175])

In [161]:
SP_VT1b_SST = SP_VT1B_table[SP_VT1B_table['cre_line'] == 'Sst-IRES-Cre']
SP_VT1b_SST.imaging_depth.unique()

array([275])

In [152]:
SP_VT_table = experiment_table[experiment_table['project_code'] == 'VisualBehavior']
SP_VT_table.head()

equipment_name  \
ophys_experiment_id                  
792815735                  CAM2P.4   
795073741                  CAM2P.4   
795953296                  CAM2P.4   
796108483                  CAM2P.4   
796308505                  CAM2P.4   

                                                     full_genotype  mouse_id  \
ophys_experiment_id                                                            
792815735            Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    412036   
795073741            Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    412036   
795953296            Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    412036   
796108483            Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    412036   
796308505            Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    412036   

                                  reporter_line     driver_line sex  \
ophys_experiment_id                                                   
792815735            Ai148(TIT2L-GC6f-ICL-tTA2)  [Vip-IRES-Cre]   F   
795073741            Ai148(TIT2L-GC6f-ICL-tTA2)  [Vip-IRES-Cre]   F   
795953296            Ai148(TIT2L-GC6f-ICL-tTA2)  [Vip-IRES-Cre]   F   
796108483            Ai148(TIT2L-GC6f-ICL-tTA2)  [Vip-IRES-Cre]   F   
796308505            Ai148(TIT2L-GC6f-ICL-tTA2)  [Vip-IRES-Cre]   F   

                     age_in_days      cre_line indicator  session_number  \
ophys_experiment_id                                                        
792815735                  148.0  Vip-IRES-Cre   GCaMP6f             1.0   
795073741                  151.0  Vip-IRES-Cre   GCaMP6f             3.0   
795953296                  152.0  Vip-IRES-Cre   GCaMP6f             4.0   
796108483                  153.0  Vip-IRES-Cre   GCaMP6f             5.0   
796308505                  154.0  Vip-IRES-Cre   GCaMP6f             6.0   

                     prior_exposures_to_session_type  \
ophys_experiment_id                                    
792815735                                          0   
795073741                                          0   
795953296                                          0   
796108483                                          0   
796308505                                          0   

                     prior_exposures_to_image_set  \
ophys_experiment_id                                 
792815735                                    19.0   
795073741                                    21.0   
795953296                                     0.0   
796108483                                     1.0   
796308505                                     2.0   

                     prior_exposures_to_omissions  ophys_session_id  \
ophys_experiment_id                                                   
792815735                                       1         792619807   
795073741                                       3         794918442   
795953296                                       4         795625712   
796108483                                       5         796044280   
796308505                                       6         796236521   

                     behavior_session_id  ophys_container_id    project_code  \
ophys_experiment_id                                                            
792815735                      792680306           791352433  VisualBehavior   
795073741                      794968300           791352433  VisualBehavior   
795953296                      795742990           791352433  VisualBehavior   
796108483                      796052844           791352433  VisualBehavior   
796308505                      796251270           791352433  VisualBehavior   

                     imaging_depth targeted_structure  \
ophys_experiment_id                                     
792815735                      175               VISp   
795073741                      175               VISp   
795953296                      175               VISp   
796108483                      175               VIS

In [153]:
SP_VT_table.imaging_depth.unique()

array([175, 375, 290, 275])

How many planes were imaged for VIP cells in visual task-Single plane dataset? 


In [156]:
SP_VT_VIP = SP_VT_table[SP_VT_table['cre_line'] == 'Vip-IRES-Cre']
SP_VT_VIP.imaging_depth.unique()

array([175])

In [ ]:
How many planes were imaged for sst cells in visual task-Single plane dataset?? 


In [162]:
SP_VT_SST = SP_VT_table[SP_VT_table['cre_line'] == 'Sst-IRES-Cre']
SP_VT_SST.imaging_depth.unique()

array([290, 275])

In [146]:
single_plane_sst = single_plane_table2[single_plane_table2['cre_line'] == 'Sst-IRES-Cre']
single_plane_sst.head()

equipment_name  \
ophys_experiment_id                  
960957793                  CAM2P.5   
961283857                  CAM2P.5   
962471831                  CAM2P.5   
965228792                  CAM2P.5   
965930965                  CAM2P.5   

                                                     full_genotype  mouse_id  \
ophys_experiment_id                                                            
960957793            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    467302   
961283857            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    467302   
962471831            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    467302   
965228792            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    467302   
965930965            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    467302   

                                  reporter_line     driver_line sex  \
ophys_experiment_id                                                   
960957793            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   
961283857            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   
962471831            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   
965228792            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   
965930965            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   M   

                     age_in_days      cre_line indicator  session_number  \
ophys_experiment_id                                                        
960957793                  173.0  Sst-IRES-Cre   GCaMP6f             1.0   
961283857                  174.0  Sst-IRES-Cre   GCaMP6f             2.0   
962471831                  177.0  Sst-IRES-Cre   GCaMP6f             3.0   
965228792                  180.0  Sst-IRES-Cre   GCaMP6f             4.0   
965930965                  181.0  Sst-IRES-Cre   GCaMP6f             5.0   

                     prior_exposures_to_session_type  \
ophys_experiment_id                                    
960957793                                          1   
961283857                                          0   
962471831                                          0   
965228792                                          0   
965930965                                          0   

                     prior_exposures_to_image_set  \
ophys_experiment_id                                 
960957793                                    27.0   
961283857                                    28.0   
962471831                                    29.0   
965228792                                     0.0   
965930965                                     1.0   

                     prior_exposures_to_omissions  ophys_session_id  \
ophys_experiment_id                                                   
960957793                                       1         960749169   
961283857                                       2         961226856   
962471831                                       3         962206869   
965228792                                       6         964912357   
965930965                                       7         965615627   

                     behavior_session_id  ophys_container_id    project_code  \
ophys_experiment_id                                                            
960957793                      960834330           957024596  VisualBehavior   
961283857                      961246494           957024596  VisualBehavior   
962471831                      962346335           957024596  VisualBehavior   
965228792                      965034185           957024596  VisualBehavior   
965930965                      965727499           957024596  VisualBehavior   

                     imaging_depth targeted_structure  \
ophys_experiment_id                                     
960957793                      290               VISp   
961283857                      290               VISp   
962471831                      290               VISp   
965228792                      290               VIS

In [149]:
single_plane_sst.imaging_depth.unique()

array([290, 275])

In [148]:
single_plane_sst.targeted_structure.unique()

array(['VISp'], dtype=object)

In [130]:
multi_plane_table = experiment_table[experiment_table['project_code'] == 'VisualBehaviorMultiscope']
multi_plane_table.head()

equipment_name  \
ophys_experiment_id                  
951980471                   MESO.1   
951980484                   MESO.1   
951980473                   MESO.1   
951980479                   MESO.1   
951980475                   MESO.1   

                                                     full_genotype  mouse_id  \
ophys_experiment_id                                                            
951980471            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
951980484            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
951980473            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
951980479            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   
951980475            Sst-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt    457841   

                                  reporter_line     driver_line sex  \
ophys_experiment_id                                                   
951980471            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   
951980484            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   
951980473            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   
951980479            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   
951980475            Ai148(TIT2L-GC6f-ICL-tTA2)  [Sst-IRES-Cre]   F   

                     age_in_days      cre_line indicator  session_number  \
ophys_experiment_id                                                        
951980471                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   
951980484                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   
951980473                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   
951980479                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   
951980475                  206.0  Sst-IRES-Cre   GCaMP6f             1.0   

                     prior_exposures_to_session_type  \
ophys_experiment_id                                    
951980471                                          0   
951980484                                          0   
951980473                                          0   
951980479                                          0   
951980475                                          0   

                     prior_exposures_to_image_set  \
ophys_experiment_id                                 
951980471                                    65.0   
951980484                                    65.0   
951980473                                    65.0   
951980479                                    65.0   
951980475                                    65.0   

                     prior_exposures_to_omissions  ophys_session_id  \
ophys_experiment_id                                                   
951980471                                       0         951410079   
951980484                                       0         951410079   
951980473                                       0         951410079   
951980479                                       0         951410079   
951980475                                       0         951410079   

                     behavior_session_id  ophys_container_id  \
ophys_experiment_id                                            
951980471                      951520319          1018028342   
951980484                      951520319          1018028351   
951980473                      951520319          1018028345   
951980479                      951520319          1018028354   
951980475                      951520319          1018028339   

                                 project_code  imaging_depth  \
ophys_experiment_id                                            
951980471            VisualBehaviorMultiscope            150   
951980484            VisualBehaviorMultiscope             75   
951980473            VisualBehaviorMultiscope            225   
951980479            VisualBehaviorMultiscope            150   
951980475            VisualBehaviorMultiscope             75   



In [131]:
multi_plane_table.imaging_depth.unique()

array([150,  75, 225, 300, 359,  85, 271,  73, 169, 263, 167,  79, 361,
       267, 363, 275, 175, 367, 269, 177, 283, 365, 373, 371, 165,  81,
       369,  77, 171, 259, 377, 279,  83, 274, 227, 152, 146,  71, 276,
       144, 158, 142,  87, 160, 217,  69, 219,  51, 140, 215, 156, 211,
       162, 221, 148, 166, 223, 231, 282, 174,  93, 213, 154, 229, 302,
       308, 298, 278, 306, 270, 312, 218, 383, 161, 273, 381, 265, 261,
       310, 235, 292, 296, 187, 295, 197,  91, 183, 355, 277, 179, 181,
       281, 185, 291,  95, 375, 173,  67, 284, 320, 145, 285, 321, 228,
       149, 287, 322, 220, 222, 226, 147, 294, 315, 304, 286, 316, 132,
       350, 348,  65, 379])

In [164]:
multi_plane_table_sst = multi_plane_table[multi_plane_table['cre_line'] == 'Sst-IRES-Cre']
multi_plane_table_sst.head()
multi_plane_table_sst.imaging_depth.unique()

array([150,  75, 225, 300, 154, 158, 156,  83, 235, 284, 320, 144, 145,
       285, 221, 321, 228, 149, 287, 292, 148, 213, 218, 229, 322, 220,
       152, 222, 146, 226, 147, 294, 315, 227, 175, 275, 350, 348,  65,
       167, 283, 179,  71,  81, 183])

In [166]:
multi_plane_table_vip = multi_plane_table[multi_plane_table['cre_line'] == 'Vip-IRES-Cre']
multi_plane_table_vip.head()
multi_plane_table_vip.imaging_depth.unique()

array([ 75, 225, 150, 274, 227, 275,  73, 152, 146,  71, 276, 144, 158,
       142,  87, 160, 217,  69, 219,  51, 140, 215, 300, 156, 211, 162,
        79, 221, 148, 166,  85, 223, 231, 282, 174,  93, 213, 154, 278,
       306,  81, 270, 298, 308, 312,  77, 302, 218, 310, 235,  83, 292,
       296, 304, 229, 286, 316, 132, 294, 149])

We can also view behavior session: 